import { StyleSheet } from 'react-native';
import colors from '../../theme/colors';

export const createBuzzStyles = StyleSheet.create({
  fab: {
    position: 'absolute',
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(24,24,27,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.4)',
    borderRadius: 28,
    paddingVertical: 10,
    paddingLeft: 12,
    paddingRight: 18,
    zIndex: 40,
    shadowColor: '#22c55e',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  fabDisabled: {
    opacity: 0.45,
  },
  fabIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabIconText: {
    color: '#000',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  fabLabel: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.surfaceElevated,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: 'hidden',
    maxHeight: '92%',
  },
  sheetScrollView: {
    backgroundColor: colors.surfaceElevated,
  },
  sheetScroll: {
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  headerStrip: {
    height: 4,
    backgroundColor: '#22c55e',
    borderRadius: 2,
    marginBottom: 20,
    width: 48,
    alignSelf: 'center',
  },
  title: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '900',
    fontStyle: 'italic',
    textTransform: 'uppercase',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  subtitle: {
    color: '#71717a',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 20,
  },
  label: {
    color: '#a1a1aa',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginTop: 12,
  },
  typeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  typeChipActive: {
    borderColor: '#22c55e',
    backgroundColor: 'rgba(34,197,94,0.12)',
  },
  typeChipText: {
    color: '#a1a1aa',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  typeChipTextActive: {
    color: '#fff',
  },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#3f3f46',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    color: '#fff',
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  sliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sliderHeaderText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  sliderHeaderSubtext: {
    color: '#9ca3af',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  sliderContainer: {
    marginBottom: 16,
  },
  sliderTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#273449',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#22c55e',
    borderRadius: 999,
  },
  sliderStep: {
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -6 }, { translateX: -6 }],
    width: 12,
    height: 12,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sliderStepActive: {
    top: '50%',
  },
  sliderStepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
  },
  sliderStepDotActive: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  sliderThumb: {
    position: 'absolute',
    top: '50%',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0f172a',
    borderWidth: 2,
    borderColor: '#22c55e',
    transform: [{ translateX: -14 }, { translateY: -14 }],
    shadowColor: '#22c55e',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  sliderLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sliderLabelWrap: {
    flex: 1,
    alignItems: 'center',
  },
  sliderLabel: {
    color: '#9ca3af',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sliderLabelActive: {
    color: '#fff',
  },
  secretRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingVertical: 8,
  },
  secretLabel: {
    color: '#ef4444',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.border,
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  toggleOn: {
    backgroundColor: 'rgba(239,68,68,0.35)',
    borderWidth: 1,
    borderColor: '#ef4444',
  },
  toggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#71717a',
  },
  toggleKnobOn: {
    alignSelf: 'flex-end',
    backgroundColor: '#ef4444',
  },
  errorBox: {
    backgroundColor: 'rgba(127,29,29,0.35)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.5)',
    borderRadius: 16,
    padding: 14,
    marginTop: 12,
    marginBottom: 4,
  },
  errorText: {
    color: '#fecaca',
    fontSize: 13,
    lineHeight: 18,
  },
  hint: {
    color: '#71717a',
    fontSize: 11,
    marginTop: 8,
    marginBottom: 8,
    lineHeight: 16,
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  cancelBtnText: {
    color: '#a1a1aa',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  submitBtn: {
    flex: 2,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    backgroundColor: '#f8fafc',
  },
  submitBtnDisabled: {
    opacity: 0.5,
  },
  submitBtnText: {
    color: '#0f172a',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  closeBtn: {
    position: 'absolute',
    top: 16,
    right: 20,
    zIndex: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtnText: {
    color: '#a1a1aa',
    fontSize: 16,
  },
});
