import { StyleSheet } from "react-native";
import colors from "../../theme/colors";

export const createBuzzStyles = StyleSheet.create({
  fab: {
    position: "absolute",
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(26,1,61,0.96)",
    borderWidth: 1,
    borderColor: "rgba(83,172,117,0.4)",
    borderRadius: 28,
    paddingVertical: 10,
    paddingLeft: 12,
    paddingRight: 18,
    zIndex: 40,
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  fabDisabled: {
    opacity: 0.45,
  },
  fabIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  fabIconText: {
    color: colors.secondary,
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    includeFontPadding: false,
  },
  fabLabel: {
    color: colors.text,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.surfaceElevated,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: "hidden",
    maxHeight: "92%",
  },
  sheetScrollView: {
    backgroundColor: colors.surfaceElevated,
  },
  sheetScroll: {
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  headerStrip: {
    height: 4,
    backgroundColor: colors.primary,
    borderRadius: 2,
    marginBottom: 20,
    width: 48,
    alignSelf: "center",
  },
  title: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "900",
    fontStyle: "italic",
    textTransform: "uppercase",
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  subtitle: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 20,
  },
  label: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: 12,
  },
  typeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  typeChipActive: {
    borderColor: colors.primary,
    backgroundColor: "rgba(83,172,117,0.12)",
  },
  typeChipText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  typeChipTextActive: {
    color: colors.text,
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    color: colors.text,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  sliderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sliderHeaderText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  sliderHeaderSubtext: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  sliderContainer: {
    marginBottom: 16,
  },
  sliderTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "rgba(83,172,117,0.18)",
    overflow: "hidden",
    position: "relative",
    justifyContent: "center",
  },
  sliderFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.primary,
    borderRadius: 999,
  },
  sliderStep: {
    position: "absolute",
    top: "50%",
    transform: [{ translateY: -6 }, { translateX: -6 }],
    width: 12,
    height: 12,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  sliderStepActive: {
    top: "50%",
  },
  sliderStepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "rgba(83,172,117,0.2)",
  },
  sliderStepDotActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  sliderThumb: {
    position: "absolute",
    top: "50%",
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.primary,
    transform: [{ translateX: -14 }, { translateY: -14 }],
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  sliderLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sliderLabelWrap: {
    flex: 1,
    alignItems: "center",
  },
  sliderLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  sliderLabelActive: {
    color: colors.text,
  },
  secretRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
    paddingVertical: 8,
  },
  secretLabel: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.border,
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  toggleOn: {
    backgroundColor: "rgba(83,172,117,0.35)",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  toggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.muted,
  },
  toggleKnobOn: {
    alignSelf: "flex-end",
    backgroundColor: colors.primary,
  },
  errorBox: {
    backgroundColor: "rgba(127,29,29,0.35)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.5)",
    borderRadius: 16,
    padding: 14,
    marginTop: 12,
    marginBottom: 4,
  },
  errorText: {
    color: "#fca5a5",
    fontSize: 13,
    lineHeight: 18,
  },
  hint: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 8,
    marginBottom: 8,
    lineHeight: 16,
  },
  actions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    backgroundColor: colors.background,
  },
  cancelBtnText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  submitBtn: {
    flex: 2,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    backgroundColor: colors.plain,
  },
  submitBtnDisabled: {
    opacity: 0.5,
  },
  submitBtnText: {
    color: colors.secondary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  closeBtn: {
    position: "absolute",
    top: 16,
    right: 20,
    zIndex: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  closeBtnText: {
    color: colors.muted,
    fontSize: 16,
  },
});
